#ALL=eap_auth_ll_test eap_peer_ll_test 
ALL=libeap.a
all: $(ALL)


ifndef CC
CC=gcc
endif

ifndef RANLIB
RANLIB=ranlib
endif

ifndef CFLAGS
CFLAGS = -O2 -Wall -g
endif


CFLAGS += -I.
CFLAGS += -I../wpa_supplicant/src
CFLAGS += -I../wpa_supplicant/src/utils

OBJS_both = ../wpa_supplicant/src/radius/*.o
OBJS_both += ../wpa_supplicant/src/crypto/*.o
OBJS_both += ../wpa_supplicant/src/utils/*.o
OBJS_both +=  ../wpa_supplicant/src/tls/libtls.a


OBJS_both += ../wpa_supplicant/src/eap_common/eap_peap_common.o
OBJS_both += ../wpa_supplicant/src/eap_common/eap_psk_common.o
OBJS_both += ../wpa_supplicant/src/eap_common/eap_pax_common.o
OBJS_both += ../wpa_supplicant/src/eap_common/eap_sake_common.o
OBJS_both += ../wpa_supplicant/src/eap_common/eap_gpsk_common.o
OBJS_both += ../wpa_supplicant/src/eap_common/chap.o
OBJS_both += ../wpa_supplicant/wpa_supplicant/config_file.o
OBJS_both += ../wpa_supplicant/wpa_supplicant/config.o

OBJS_peer += ../wpa_supplicant/src/eap_peer/eap_tls.o
OBJS_peer += ../wpa_supplicant/src/eap_peer/eap_peap.o
OBJS_peer += ../wpa_supplicant/src/eap_peer/eap_ttls.o
OBJS_peer += ../wpa_supplicant/src/eap_peer/eap_md5.o
OBJS_peer += ../wpa_supplicant/src/eap_peer/eap_mschapv2.o
OBJS_peer += ../wpa_supplicant/src/eap_peer/mschapv2.o
OBJS_peer += ../wpa_supplicant/src/eap_peer/eap_otp.o
OBJS_peer += ../wpa_supplicant/src/eap_peer/eap_gtc.o
OBJS_peer += ../wpa_supplicant/src/eap_peer/eap_leap.o
OBJS_peer += ../wpa_supplicant/src/eap_peer/eap_psk.o
OBJS_peer += ../wpa_supplicant/src/eap_peer/eap_pax.o
OBJS_peer += ../wpa_supplicant/src/eap_peer/eap_sake.o
OBJS_peer += ../wpa_supplicant/src/eap_peer/eap_gpsk.o
OBJS_peer += ../wpa_supplicant/src/eap_peer/eap.o
OBJS_peer += ../wpa_supplicant/src/eap_common/eap_common.o
OBJS_peer += ../wpa_supplicant/src/eap_peer/eap_methods.o
OBJS_peer += ../wpa_supplicant/src/eap_peer/eap_tls_common.o
OBJS_peer += eap_peer_interface.o


CFLAGS += -DEAP_TLS
CFLAGS += -DEAP_PEAP
CFLAGS += -DEAP_TTLS
CFLAGS += -DEAP_MD5
CFLAGS += -DEAP_MSCHAPv2
CFLAGS += -DEAP_GTC
CFLAGS += -DEAP_OTP
CFLAGS += -DEAP_LEAP
CFLAGS += -DEAP_PSK
CFLAGS += -DEAP_PAX
CFLAGS += -DEAP_SAKE
CFLAGS += -DEAP_GPSK -DEAP_GPSK_SHA256

CFLAGS += -DEAP_SERVER_IDENTITY
CFLAGS += -DEAP_SERVER_TLS
CFLAGS += -DEAP_SERVER_PEAP
CFLAGS += -DEAP_SERVER_TTLS
CFLAGS += -DEAP_SERVER_MD5
CFLAGS += -DEAP_SERVER_MSCHAPV2
CFLAGS += -DEAP_SERVER_GTC
CFLAGS += -DEAP_SERVER_PSK
CFLAGS += -DEAP_SERVER_PAX
CFLAGS += -DEAP_SERVER_SAKE
CFLAGS += -DEAP_SERVER_GPSK -DEAP_SERVER_GPSK_SHA256

CFLAGS += -DIEEE8021X_EAPOL


# Optional components to add EAP server support
OBJS_server += ../wpa_supplicant/src/eap_server/eap_server_tls.o
OBJS_server += ../wpa_supplicant/src/eap_server/eap_server_peap.o
OBJS_server += ../wpa_supplicant/src/eap_server/eap_server_ttls.o
OBJS_server += ../wpa_supplicant/src/eap_server/eap_server_md5.o
OBJS_server += ../wpa_supplicant/src/eap_server/eap_server_mschapv2.o
OBJS_server += ../wpa_supplicant/src/eap_server/eap_server_gtc.o
OBJS_server += ../wpa_supplicant/src/eap_server/eap_server_psk.o
OBJS_server += ../wpa_supplicant/src/eap_server/eap_server_pax.o
OBJS_server += ../wpa_supplicant/src/eap_server/eap_server_sake.o
OBJS_server += ../wpa_supplicant/src/eap_server/eap_server_gpsk.o
OBJS_server += ../wpa_supplicant/src/eap_server/eap_server.o
OBJS_server += ../wpa_supplicant/src/eap_server/eap_server_identity.o
OBJS_server += ../wpa_supplicant/src/eap_server/eap_server_methods.o
OBJS_server += ../wpa_supplicant/src/eap_server/eap_server_tls_common.o
OBJS_server += eap_auth_interface.o
CFLAGS += -DEAP_SERVER


ifndef LDO
LDO=$(CC)
endif

Q=@
E=echo
ifeq ($(V), 1)
Q=
E=true
endif

%.o: %.c
	$(Q)$(CC) -c -o $@ $(CFLAGS) $<
	@$(E) "  CC " $<


OBJS_lib=$(OBJS_both) $(OBJS_peer) $(OBJS_server)

#OBJS_ex = eap_auth_ll_test.o
#OBJS_peer_ll = eap_peer_ll_test.o

../wpa_supplicant/src/utils/*.o:
	$(MAKE) -C ../wpa_supplicant/src/utils

../wpa_supplicant/src/crypto/*.o:
	$(MAKE) -C ../wpa_supplicant/src/crypto

../wpa_supplicant/src/tls/libtls.a:
	$(MAKE) -C ../wpa_supplicant/src/tls

../wpa_supplicant/src/radius/*.o:
	$(MAKE) -C ../wpa_supplicant/src/radius        

#ifneq ($(CONFIG_SOLIB), yes)
#LIBEAP = libeap.a
libeap.a: $(OBJS_lib)
	$(AR) crT libeap.a $(OBJS_lib)
	$(RANLIB) libeap.a

#else
#CFLAGS  += -fPIC -DPIC
#LDFLAGS += -shared

#LIBEAP  = libeap.so
#libeap.so: $(OBJS_lib)
#	$(LDO) $(LDFLAGS) $(OBJS_lib) -o $(LIBEAP)

#endif

#eap_auth_ll_test: $(OBJS_ex) $(LIBEAP)
#	$(LDO) -o eap_auth_ll_test $(OBJS_ex) $(LIBS) -L. -leap

#eap_peer_ll_test: $(OBJS_peer_ll) $(LIBEAP)
#	$(LDO) -o eap_peer_ll_test $(OBJS_peer_ll) $(LIBS) -L. -leap        

clean:
	$(MAKE) -C ../wpa_supplicant/src clean
	rm -f core *~ *.o *.d libeap.a libeap.so $(ALL)




-include $(OBJS:%.o=%.d)
